Homework \#3
================
Sneha Mehta
2022-10-15

## Problem 1

``` r
data("instacart")

instacart = 
  instacart %>% 
  as_tibble(instacart)
```

This dataset includes 1,384,617 observations across 15 variables. It
describes orders placed on Instacart by 131,209 unique customers.
Variables in the dataset include the time each order was placed (day of
the week and hour of the day), names of products in the order, isle and
department products are found (number and name (i.e., soft drinks,
dairy, produce, household goods)), and days since last order.

``` r
instacart %>% 
  count(aisle) %>% 
  arrange(desc(n)) %>% view()
```

There are 134 aisles. The aisles with the most number of items ordered
are fresh vegetables and fresh fruits at 150609 and 150473 items
respectively.

``` r
instacart %>% 
  count(aisle) %>% 
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  ggplot(aes(x = aisle, y = n)) + 
  geom_point() + 
  labs(title = "Number of items ordered in each aisle") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

<img src="p8105_hw3_sm5134_files/figure-gfm/prob 1 part 2-1.png" width="90%" />
This plot shows all the aisles with at least 10,000 items bought from
them. Most aisles have 40,000 items or less purchased from them.

``` r
instacart %>% 
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>%
  group_by(aisle) %>% 
  count(product_name) %>% 
  mutate(rank = min_rank(desc(n))) %>% 
  filter(rank < 4) %>% 
  arrange(desc(n)) %>%
  knitr::kable()
```

| aisle                      | product_name                                  |    n | rank |
|:---------------------------|:----------------------------------------------|-----:|-----:|
| packaged vegetables fruits | Organic Baby Spinach                          | 9784 |    1 |
| packaged vegetables fruits | Organic Raspberries                           | 5546 |    2 |
| packaged vegetables fruits | Organic Blueberries                           | 4966 |    3 |
| baking ingredients         | Light Brown Sugar                             |  499 |    1 |
| baking ingredients         | Pure Baking Soda                              |  387 |    2 |
| baking ingredients         | Cane Sugar                                    |  336 |    3 |
| dog food care              | Snack Sticks Chicken & Rice Recipe Dog Treats |   30 |    1 |
| dog food care              | Organix Chicken & Brown Rice Recipe           |   28 |    2 |
| dog food care              | Small Dog Biscuits                            |   26 |    3 |

The most popular items from the packaged vegetables & fruits, baking
ingredients, and dog food care aisles are organic baby spinach
(purchased 9784 times), light brown sugar (499 times), and Snack Sticks
Chicken & Rice Recipe Dog Treats (30 times) respectively.

``` r
instacart %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  summarize(mean_hour = mean(order_hour_of_day)) %>%
  spread(key = order_dow, value = mean_hour) %>%
  knitr::kable(digits = 2)
```

    ## `summarise()` has grouped output by 'product_name'. You can override using the
    ## `.groups` argument.

| product_name     |     0 |     1 |     2 |     3 |     4 |     5 |     6 |
|:-----------------|------:|------:|------:|------:|------:|------:|------:|
| Coffee Ice Cream | 13.77 | 14.32 | 15.38 | 15.32 | 15.22 | 12.26 | 13.83 |
| Pink Lady Apples | 13.44 | 11.36 | 11.70 | 14.25 | 11.55 | 12.78 | 11.94 |

Generally speaking, Pink Lady Apples are purchased earlier in the day
than Coffee Ice Cream except for on Day 5

## Problem 2

``` r
accel_data = read_csv("./accel_data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(day_type = ifelse(day == "Saturday" | day == "Sunday", "weekend", "weekday")) %>% 
  relocate(day_type, .after = day) %>% 
  pivot_longer(activity_1:activity_1440,
               names_to = "minute",
               names_prefix = "activity_",
               values_to = "activity_count") %>% 
  mutate(minute = as.numeric(minute))
```

    ## Rows: 35 Columns: 1443
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr    (1): day
    ## dbl (1442): week, day_id, activity.1, activity.2, activity.3, activity.4, ac...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

This dataset describes five weeks of accelerometer data collected from a
63 year old male with BMI 25. Activity counts were collected each minute
of the days. The tidied dataset has 50,400 observations across six
variables: the week and day of data collection (day is listed
numerically, by day of the week, and classified as a weekday or
weekend), the minute of the day the activity count was collected, and
the activity count.

``` r
accel_data_sum = accel_data %>% 
  group_by(week, day) %>% 
  summarise(day_activity_total = sum(activity_count)) %>% 
  pivot_wider(
    names_from = day,
    values_from = day_activity_total) %>% 
  select("week", "Monday","Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
```

    ## `summarise()` has grouped output by 'week'. You can override using the
    ## `.groups` argument.

``` r
accel_data_sum %>% group_by() %>% 
  summarise(across(Monday:Sunday, mean)) %>% view()
```

On average, Saturdays had the lowest activity counts for the individual.
Wednesdays - Fridays had the highest.

``` r
ggplot(accel_data, aes(x = minute/60, y = activity_count)) + geom_line(aes(color = day)) + geom_point(aes(color = day), alpha = 0.5) + geom_smooth() + labs(
  title = "Daily Activity Levels",
  x = "Hour",
  y = "Activity Count"
)
```

    ## `geom_smooth()` using method = 'gam' and formula 'y ~ s(x, bs = "cs")'

<img src="p8105_hw3_sm5134_files/figure-gfm/prob 2 part 3-1.png" width="90%" />
From this plot, we can see that most activity for this person took place
between \~8:00 - \~21:00 hours each day. Activity dipped quite sharply
at around 21:00 hours each day and gradually rose from \~5:00 to \~9:00
hours and mostly plateaued for the middle part of each day.

## Problem 3

``` r
library(p8105.datasets)
data("ny_noaa") 
```

This dataset has 2,595,176 observations across 7 variables. It contains
data from all New York state weather stations across 5 metrics:
precipitation, snowfall, snow depth, maximum temperature, and minimum
temperature. It also includes date of observation and the id number of
the weather station. There are large amounts of missing observations
across all 5 of the measurement metrics.

``` r
ny_noaa = ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), sep = "-", convert = TRUE) %>% 
  mutate(tmax = as.numeric(tmax)/10, 
         tmin = as.numeric(tmin)/10,
         prcp = prcp/10)

table(ny_noaa$snow)
```

    ## 
    ##     -13       0       3       5       8      10      13      15      18      20 
    ##       1 2008508    8790    9748    9962    5106   23095    3672    3226    4797 
    ##      23      25      28      30      33      36      38      41      43      46 
    ##    1959   31022    2118    2814    2380    1630    9197    1467    1337    2123 
    ##      48      51      53      56      58      61      64      66      69      71 
    ##     918   18274    1155    1179    1198     849    4506     790     726    1075 
    ##      74      76      79      81      84      86      89      91      94      97 
    ##     463   10173     635     811     553     476    2535     428     404     704 
    ##      99     102     104     107     109     112     114     117     119     122 
    ##     276    6552     349     504     393     243    1578     276     248     411 
    ##     124     127     130     132     135     137     140     142     145     147 
    ##     183    3901     217     310     253     173     994     187     172     268 
    ##     150     152     155     157     160     163     165     168     170     173 
    ##     124    3131     186     209     149     133     614     115     104     187 
    ##     175     178     180     183     185     188     191     193     196     198 
    ##      80    1650      93     132     117      77     426      70      75     130 
    ##     201     203     206     208     211     213     216     218     221     224 
    ##      60    1475      74      98      69      58     292      55      53      61 
    ##     226     229     231     234     236     239     241     244     246     249 
    ##      35     744      43      52      49      39     192      36      37      58 
    ##     251     254     257     259     262     264     267     269     272     274 
    ##      21     786      34      48      28      24     130      19      22      45 
    ##     277     279     282     284     287     290     292     295     297     300 
    ##      20     369      28      37      22      24      81      20      14      24 
    ##     302     305     307     310     312     315     318     320     323     325 
    ##      22     451      17      29      22      13      70       7      22      12 
    ##     328     330     333     335     338     340     343     345     348     351 
    ##       6     226       9      13      17      13      63      17       6      15 
    ##     353     356     358     361     363     366     368     371     373     376 
    ##      12     235      12      15      14      15      32       4       6      12 
    ##     378     381     384     386     389     391     394     396     399     401 
    ##       5     139       6       8       5       1      27       5       4      10 
    ##     404     406     409     411     414     417     419     422     424     427 
    ##       7     116       6       8      12       9      15       5       3       8 
    ##     429     432     434     437     439     445     447     450     452     455 
    ##       1      63       7       8       3       8       5       5       5       4 
    ##     457     460     462     465     467     470     472     475     478     480 
    ##     100       5       3       5       6      20       4       5       4       2 
    ##     483     488     490     495     498     503     505     508     511     513 
    ##      44       4       2       3       2       2       2      54       2       3 
    ##     516     518     521     523     526     528     533     536     544     546 
    ##       2       3       8       2       2       2      16       1       1       6 
    ##     549     551     554     556     559     561     564     566     569     572 
    ##       4       2       4       1      35       2       2       1       1       3 
    ##     574     577     579     584     587     589     592     594     597     607 
    ##       1       1       1      20       1       1       2       3       4       1 
    ##     610     612     615     620     622     625     630     632     635     643 
    ##      35       1       1       1       2       1       2       3      10       2 
    ##     645     648     650     660     663     665     686     693     699     704 
    ##       1       1       1      13       2       1       6       1       4       1 
    ##     711     721     734     737     754     762     775     787     808     810 
    ##      10       2       1       9       1      17       3       4       1       1 
    ##     813     838     843     861     864     871     892     914     940     953 
    ##       2       2       1       1       2       1       1       4       1       1 
    ##     965     978    1041    1067    1105    1143    1207    6350    7122    7765 
    ##       1       1       1       1       1       1       1       1       1       1 
    ##   10160 
    ##       1

``` r
sort(table(ny_noaa$snow), decreasing = TRUE) %>% view()
```

The most commonly observed value for snowfall is 0mm due to the fact
that the snowy season is mainly concentrated in a few months (Dec-Feb)
(and even then it doesn’t snow every day).

``` r
ny_noaa %>% 
  filter(month == 1 | month == 7) %>% mutate(month = case_when(month == 1 ~ "January",
                                                               month == 7 ~ "July")) %>% 
  group_by(id, year, month) %>% 
  mutate(avgtmax = mean(tmax)) %>% 
  ggplot(aes(x = year, y = avgtmax)) + geom_line(aes(color = id), alpha = 0.5) + facet_grid(.~ month) + theme(legend.position = "none") + labs(
  title = "Average Max. Temperature by Month per Station",
  x = "Time",
  y = "Average Max. Temp"
)
```

<img src="p8105_hw3_sm5134_files/figure-gfm/prob 3 part 2-1.png" width="90%" />
From the plots, we can see that the average temperature in January is
\~27 degrees lower than the average temperature in July. The
temperatures in January generally range between around -10 to 10 degrees
Celsius, and in July, the temperatures generally range from 20-35
degrees Celcius. In July, we can see one obvious outlier where in \~1988
one station recorded temperatures around 15 degrees.

``` r
min_max = ggplot(ny_noaa, aes(x = tmin, y = tmax)) + geom_hex() + labs(
  x = "Minimum Temp",
  y = "Maximum Temp", 
  title = "Maximum Temp vs Minimum Temp in New York 1981 - 2010"
)
min_max
```

<img src="p8105_hw3_sm5134_files/figure-gfm/prob 3 part 3-1.png" width="90%" />

``` r
snowfall = ny_noaa %>% 
  filter(snow %in% (1:99)) %>% 
  ggplot(aes(x = snow, y = as.factor(year), group = year)) + geom_density_ridges() + labs(
    x = "Snowfall(mm)",
    y = "Year",
    title = "Snowfall by Year in New York 1981 - 2010"
  )
snowfall
```

    ## Picking joint bandwidth of 3.76

<img src="p8105_hw3_sm5134_files/figure-gfm/prob 3 part 3-2.png" width="90%" />

``` r
min_max + snowfall
```

    ## Picking joint bandwidth of 3.76

<img src="p8105_hw3_sm5134_files/figure-gfm/prob 3 part 3-3.png" width="90%" />
Within the time range, the highest number of days had a minimum
temperature between \~0-15 degrees Celsius and a maximum temperature
between \~0-30 degrees. Across the time range, the most common level of
snowfall measured per day was between 0-30 mm. There was also a peak
around 40-50mm.
